
 services:
   app:
     build:
       context: .
       dockerfile: Dockerfile
     container_name: symfony_app
     ports:
       - "9000:9000"
     environment:
       APP_ENV: dev
     volumes:
       - .:/var/www/symfony
     depends_on:
       - db

   web:
     image: nginx:1.23
     container_name: symfony_nginx
     ports:
       - "8080:8080"
     volumes:
       - .:/var/www/symfony
       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
     depends_on:
       - app

   db:
     image: mysql:8.0
     container_name: symfony_db
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: symfony
       MYSQL_USER: symfony
       MYSQL_PASSWORD: symfony
     ports:
       - "3306:3306"
     volumes:
       - db_data:/var/lib/mysql
   phpma:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        PMA_ARBITRARY: 1
        PMA_HOST: db
        PMA_USER: root
        PMA_PASSWORD: root
        UPLOAD_LIMIT: 20M
      ports: 
        - 8081:80

 volumes:
   db_data: